title: Tala's Little Corner of the Web
author: Marlene Witsch
email: marlenewitsch@gmail.com
description:
  Talasa lerning new things and trying them out. 

twitter_username: Talasa_S
github_username: TalasaSilverwind

show_excerpts: true

theme: jekyll-theme-midnight
